### ISSUE TITLE
채점 현황에서 랜덤게임같은 문제들 제외하고 볼수 있게 해주시면 감사합니다

### ISSUE THREAD

**Issue by loonfactory** [Startlink/update-note#1]

**Comment by Baekjoon** [comment]
이 기능은 최근 제출된 문제와 최근 풀린 문제 메뉴를 통해서 지원하고 있습니다. 
m

**Comment by Baekjoon** [comment]
기능 추가 요청은 https://github.com/Startlink/BOJ-Feature-Request 이쪽을 이용해주세요.
